name: http_interceptor_example
description: Demonstrates how to use the http_interceptor plugin.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http_interceptor:
    path: ../
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
