name: http_interceptor_example
description: Demonstrates how to use the http_interceptor plugin.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http_interceptor:
    path: ../
  image_picker: ^0.8.8
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
