include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    close_sinks: true
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    require_trailing_commas: true