name: http_interceptor
description:
  A lightweight, simple plugin that allows you to intercept request and response
  objects and modify them if desired.
version: 2.0.0-beta.8
homepage: https://github.com/CodingAleCR/http_interceptor
issue_tracker: https://github.com/CodingAleCR/http_interceptor/issues
repository: https://github.com/CodingAleCR/http_interceptor

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
