name: http_interceptor
description:
  A lightweight, simple plugin that allows you to intercept request and response
  objects and modify them if desired.
version: 2.0.0
homepage: https://github.com/CodingAleCR/http_interceptor
issue_tracker: https://github.com/CodingAleCR/http_interceptor/issues
repository: https://github.com/CodingAleCR/http_interceptor

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  http: ^1.2.1
  qs_dart: ^1.3.5+1
  validators: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
