name: http_interceptor
description: A lightweight, simple plugin that allows you to intercept request and response objects and modify them if desired.
version: 0.1.1
author: Alejandro Ulate (codingalecr) <codingalecr@gmail.com>
homepage: https://github.com/CodingAleCR/http_interceptor

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: codingalecr.http_interceptor
    pluginClass: HttpInterceptorPlugin

