name: "Init Flutter"
description: "Initializes Flutter repo"
runs:
  using: "composite"
  steps:
    - name: 📚 Checkout repository
      uses: actions/checkout@v4

    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        cache: true

    - name: 📦 Get dependencies
      shell: bash
      run: flutter pub get

    - name: ☕️ Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: 🔎 Check Flutter environment
      shell: bash
      run: flutter doctor -v